### ISSUE TITLE
Use ViroARPlaneSelector to place objects. the object position is constantly shifting.

### ISSUE THREAD

**Issue by stoneWeb** [viromedia/viro#262]
I use ViroARPlaneSelector, put a object in the plane, this object not fixed to the plane, It will move slowly according to my phone. change the original position. and sometimes change angles.
like these picture, position is not fixed.

![img_7709](https://user-images.githubusercontent.com/4115730/39504123-289a112a-4dfc-11e8-9ea5-92e01cbbaca4.PNG)
![img_7710](https://user-images.githubusercontent.com/4115730/39504124-2910dfb2-4dfc-11e8-8ccb-62efffd436bf.PNG)
![img_7711](https://user-images.githubusercontent.com/4115730/39504125-29699760-4dfc-11e8-87b0-fd9778112004.PNG)
![img_7712](https://user-images.githubusercontent.com/4115730/39504126-29c6a040-4dfc-11e8-9b05-65bd1907431c.PNG)

this is my code:
```javascript
'use strict';

import React, { Component } from 'react';

import {StyleSheet, Alert} from 'react-native';

import {
  ViroARScene,
  ViroAmbientLight,
  Viro360Video,
  Viro360Image,
  ViroUtils,
  ViroPortal,
  ViroPortalScene,
  ViroARPlane,
  ViroText,
  ViroARTrackingTargets,
  ViroARImageMarker,
  ViroSpotLight,
  ViroMaterials,
  ViroSkyBox,
  ViroNode,
  ViroController,
  ViroARPlaneSelector,
  Viro3DObject,
} from 'react-viro';

ViroMaterials.createMaterials({
  heart: {
     lightingModel: "Blinn",
     diffuseTexture: require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame_diffuse.png'),
     normalTexture: require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame_normal.png'),
     specularTexture: require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame_specular.png'),
   },
});

export default class MainScene extends Component{
  constructor(props){
      super(props)
      this.state = {
        plane: [0,0,0],
        paused: true
      }
  }
  _renderScene() {
    return (
      <ViroPortalScene passable={true}>
        <ViroPortal position={[0, 0, 0]} scale={[0.8, 0.8, 0.8]}>
          <Viro3DObject source={require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame.vrx')}
            materials={["heart"]}
            type="VRX"/>
        </ViroPortal>
        <ViroSkyBox source={{nx:require('./portal_res/sb_ocean/sb_ocean_left.jpg'),
            px:require('./portal_res/sb_ocean/sb_ocean_right.jpg'),
            ny:require('./portal_res/sb_ocean/sb_ocean_bottom.jpg'),
            py:require('./portal_res/sb_ocean/sb_ocean_top.jpg'),
            nz:require('./portal_res/sb_ocean/sb_ocean_back.jpg'),
            pz:require('./portal_res/sb_ocean/sb_ocean_front.jpg')}}/>
      </ViroPortalScene>
    )
  }
  render() {
    return (
      <ViroARScene>
        <ViroAmbientLight color="#FFFFFF" intensity={400}/>
        <ViroSpotLight position={[0, -0.5, -0.5]}
                 color="#111"
                 direction={[0, 0, -1]}
                 attenuationStartDistance={5}
                 attenuationEndDistance={10}
                 innerAngle={5}
                 outerAngle={20}/>
          <ViroARPlaneSelector minHeight={.5} minWidth={.5}>
            {this._renderScene()}
          </ViroARPlaneSelector>
      </ViroARScene>
    )
  }
}

module.exports = MainScene;
```

**Comment by achuvm** [comment]
Hi @stoneWeb,

Some drift is to be expected in conditions where the background is monotone, repetitive or muted. This is because tracking relies on the ability to find and track distinct features from the video feed.

I do want to see if you simply place some sheets of papers on the ground (to "add" more distinct features) if the tracking improves for you. Or try it in another area where the floor is more "dynamic".

Additionally, I'd recommend trying another ARCore application to see if it has the same problem (ie. the Ikea Place app: https://play.google.com/store/apps/details?id=com.inter_ikea.place&hl=en_US).

Do let us know if you see markedly difference performance between the two.

Thanks!

**Comment by achuvm** [comment]
To follow up on my previous answer, the `position` of the AR Plane is fixed, but the `rotation` is not. You can consider setting the `pauseUpdates` property of the `ViroARPlaneSelector` to `true` in order to stop the updates as soon as you are ready to display your object. This will prevent the object from rotating as ARCore updates its understanding of the AR Plane, but the position should remain constant (use the `center` value returned in `onAnchorUpdated` if you'd like to keep your objects at the center of the found plane).

**Comment by stoneWeb** [comment]
Thanks for your reply, I'm going to try `pauseUpdates` property. 
I'm using ios11 arkit. I try to used another RN framework [react-native-arkit](https://github.com/react-native-ar/react-native-arkit) `onPlaneDetected` works very well, it's not some drift.

**Comment by stoneWeb** [comment]
I'm trying to set the `pauseUpdates ` property to true. It really doesn't rotate. but it will still move follow my mobile. position is not fixed. and there are computers and keyboards some thing on the plane.

**Comment by achuvm** [comment]
Hi @stoneWeb,

The `pauseUpdates` property should "fix" the rotation, but the position itself should never change.

`onAnchorUpdated` is a callback function for you to get the information about found anchors (for Planes or Image markers). If you're interested, you can print out the `Anchor`'s position to see if it actually changes: https://docs.viromedia.com/v2.6.1/docs/viroarscene#anchor

What you should see is that the `position` itself remains fixed, but the `center` (relative to the `Anchor`'s `position` and `rotation` does change).

If that is the case, then what you are observing is most likely drift. You can check this by repeatedly calling `getCameraOrientationAsync()` on the `ViroARScene` to get the camera's `position`/`rotation` as reported by ARCore.

Thanks,

**Comment by stoneWeb** [comment]
This is my `onAnchorUpdated ` position:
```
center: [ 0.17492517828941345, 0, 0.08211272954940796 ],
  position: 
   [ -0.7221636772155762,
     -0.40614646673202515,
     -0.10129033774137497 ],
  rotation: [ 0, 19.696041107177734, 0 ]

center: [ 0.17492517828941345, 0, 0.08211272954940796 ],
  position: 
   [ -0.7221636772155762,
     -0.40697383880615234,
     -0.10129033774137497 ],
  rotation: [ 0, 19.696041107177734, 0 ]

center: [ 0.17492517828941345, 0, 0.08211272954940796 ],
  position: 
   [ -0.7221636772155762,
     -0.40928828716278076,
     -0.10129033774137497 ],
  rotation: [ 0, 19.696041107177734, 0 ]

center: [ 0.18163356184959412, 0, 0.08211271464824677 ],
  position: [ -0.7221636772155762, -0.410081148147583, -0.10129033774137497 ],
  rotation: [ 0, 19.696041107177734, 0 ]

// my code
var position = [anchor.position[0] + anchor.center[0],
                    anchor.position[1] + anchor.center[1],
                    anchor.position[2] + anchor.center[2]];
    this.setState({plane: position, pausePlane: true});
<ViroPortalScene position={plane} passable={true}>
.......
</ViroPortalScene>
```
just only postion[1] is change.
so what should I do?
I put a 3d object(portal doorways) on the plane. the object always move follow my phone, It moves according to my phone position. but I rotate it flat on the plane, it works very well, it is fixed position.

**Comment by achuvm** [comment]
Hi @stoneWeb,

From what I can tell your position/center looks stable.

Looking at your code, it looks like the position of your `ViroPortal` is at [0,0,0] which means that the object is sitting halfway into the ground because the origin of that particular object is at the center of the portal. You may want to try to add some Y-value to move it up.

Can you try "walking" around it and see if it is actually moving?

I'm using a modified version of your code with a box and it's pretty stable:

```
'use strict';

import React, { Component } from 'react';

import {StyleSheet, Alert} from 'react-native';

import {
  ViroARScene,
  ViroAmbientLight,
  Viro360Video,
  Viro360Image,
  ViroUtils,
  ViroPortal,
  ViroPortalScene,
  ViroARPlane,
  ViroText,
  ViroARTrackingTargets,
  ViroARImageMarker,
  ViroSpotLight,
  ViroMaterials,
  ViroSkyBox,
  ViroNode,
  ViroController,
  ViroARPlaneSelector,
  Viro3DObject,
  ViroBox
} from 'react-viro';

export default class MainScene extends Component{
  constructor(props){
      super(props)
      this.state = {
        plane: [0,0,0],
        paused: false
      }
      this._planeSelected = this._planeSelected.bind(this);
  }
  _renderScene() {
    return (
      <ViroBox scale={[.5, 1, .1]} position={[0,.5,0]}/>
    )
  }
  _planeSelected(anchor) {
    this.setState({
      paused : true,
    })
  }
  render() {
    return (
      <ViroARScene>
        <ViroAmbientLight color="#FFFFFF" intensity={400}/>
        <ViroSpotLight position={[0, -0.5, -0.5]}
                 color="#111"
                 direction={[0, 0, -1]}
                 attenuationStartDistance={5}
                 attenuationEndDistance={10}
                 innerAngle={5}
                 outerAngle={20}/>
          <ViroARPlaneSelector minHeight={.5} minWidth={.5} pauseUpdates={this.state.paused} onPlaneSelected={this._planeSelected}>
            {this._renderScene()}
          </ViroARPlaneSelector>
      </ViroARScene>
    )
  }
}

module.exports = MainScene;
```

The only other explanation would be that ARCore is "shifting" your camera more than your movements. In this case, you can try printing out the camera position.

Thanks,

**Comment by stoneWeb** [comment]
Hi @achuvm:
I tried other components, like `ViroBox 3dObject`, work is very well. only `ViroPortalScene` is drift, not fixed position. and I tried not use ViroARPlaneSelector, and set position, It will also drift. but other components works very well.

work is ok!
```
<ViroARScene ref={ref => {this.sceneRef = ref}}>
          <ViroBox scale={[.5, 1, .1]} position={[0,.5,0]}/>
</ViroARScene>
```

not fixed position. drift to my phone.
```
<ViroPortalScene position={[0, .5, 0]} passable={true}>
        <ViroOmniLight position={[0, 1.5, 1]}
                      color="#fff"
                      direction={[0, 0, -1]}
                      attenuationStartDistance={5}
                      attenuationEndDistance={10}
                      innerAngle={5}
                      outerAngle={20}/>
        <ViroOmniLight position={[1, 1.5, -2]}
                      color="#fff"
                      direction={[0, 0, -1]}
                      attenuationStartDistance={5}
                      attenuationEndDistance={10}
                      innerAngle={5}
                      outerAngle={20}/>
        <ViroPortal scale={[0.5, 0.5, 0.5]}>
          <Viro3DObject rotation={[0, 0, 0]} source={require('./portal_res/viro_objects_portals/portal_my/a.vrx')}
            materials={["mtr"]}
            type="VRX"/>
        </ViroPortal>
        <Viro360Image source={require("./portal_res/360_waikiki.jpg")} />
      </ViroPortalScene>
```
I think you can trie the `ViroPortalScene` position.

**Comment by achuvm** [comment]
Hi @stoneWeb,

I just tried this code with a properly scaled/positioned `ViroPortal`:

`<ViroPortal position={[0, 1.244000/2, 0]} scale={[0.5, 0.5, 0.5]}>`

And it looked fine for me (see this video: https://drive.google.com/file/d/1kpUb4O-5vrz6jWDjHFYYqveaBblh3RxZ/view?usp=sharing)

There was 1 jump in the video, but otherwise it looked pretty stable.

Code that I used:
```
'use strict';

import React, { Component } from 'react';

import {StyleSheet, Alert} from 'react-native';

import {
  ViroARScene,
  ViroAmbientLight,
  Viro360Video,
  Viro360Image,
  ViroUtils,
  ViroPortal,
  ViroPortalScene,
  ViroARPlane,
  ViroText,
  ViroARTrackingTargets,
  ViroARImageMarker,
  ViroSpotLight,
  ViroMaterials,
  ViroSkyBox,
  ViroNode,
  ViroController,
  ViroARPlaneSelector,
  Viro3DObject,
} from 'react-viro';

ViroMaterials.createMaterials({
  heart: {
     lightingModel: "Blinn",
     diffuseTexture: require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame_diffuse.png'),
     normalTexture: require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame_normal.png'),
     specularTexture: require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame_specular.png'),
   },
});

export default class MainScene extends Component{
  constructor(props){
      super(props)
      this.state = {
        plane: [0,0,0],
        paused: true,
        pauseUpdates : false,
      }
  }
  _renderScene() {
    return (
      <ViroPortalScene passable={true}>
        <ViroPortal position={[0, 1.244000/2, 0]} scale={[0.5, 0.5, 0.5]}>
          <Viro3DObject source={require('./portal_res/viro_objects_portals/portal_wood_frame/portal_wood_frame.vrx')}
            materials={["heart"]}
            type="VRX"/>
        </ViroPortal>
        <ViroSkyBox source={{nx:require('./portal_res/sb_ocean/sb_ocean_left.jpg'),
            px:require('./portal_res/sb_ocean/sb_ocean_right.jpg'),
            ny:require('./portal_res/sb_ocean/sb_ocean_bottom.jpg'),
            py:require('./portal_res/sb_ocean/sb_ocean_top.jpg'),
            nz:require('./portal_res/sb_ocean/sb_ocean_back.jpg'),
            pz:require('./portal_res/sb_ocean/sb_ocean_front.jpg')}}/>
      </ViroPortalScene>
    )
  }
  render() {
    return (
      <ViroARScene>
        <ViroAmbientLight color="#FFFFFF" intensity={400}/>
        <ViroSpotLight position={[0, -0.5, -0.5]}
                 color="#111"
                 direction={[0, 0, -1]}
                 attenuationStartDistance={5}
                 attenuationEndDistance={10}
                 innerAngle={5}
                 outerAngle={20}/>
          <ViroARPlaneSelector minHeight={.5} minWidth={.5}
            onPlaneSelected={()=>{this.setState({pauseUpdates : true})}}
            pauseUpdates={this.state.pauseUpdates}>
            {this._renderScene()}
          </ViroARPlaneSelector>
      </ViroARScene>
    )
  }
}

module.exports = MainScene;
```

**Comment by japser36** [comment]
Hi I had a similar issue working on my app recently, and it turned out for me that it was because the portal object was scaled insanely huge. This could be the case if anyone stumbles across this thread in the future, unfortunately each 3D object can have its own sizing/scaling and it could be that your object is huge and far away and thus appears to move with the phone. You can verify this by also rendering a viro sphere or viro box with fixed size of for example 1 and putting it at position [0, 0, 0], then seeing if your object stays put while the viro box moves around. If that is the case, your object is just huge and in the background and you have to scale it way down and adjust its position accordingly.

**Comment by Coder108** [comment]
你好，我想问一下你用的是什么型号的手机测试的呢，我用iPhone 6s 测试但“ViroARPlane“这个不会显示出来，不知道是不是设备问题，还有就是用安卓手机测试AR功能的时候会跳到应用市场，请问是不是要支持谷歌服务的Android手机才可以正常运行
