### ISSUE TITLE
ViroVideo playing camera recorded video by rotating -90 degree

### ISSUE THREAD

**Issue by krishanjangir** [viromedia/viro#478]
Camera recorded video are played on -90 degree rotated.  While the whatsapp or other videos played in right orientation.

Original video - https://firebasestorage.googleapis.com/v0/b/odoori-de298.appspot.com/o/Videos%2F2_1543406095775.mp4?alt=media&token=9a642bc9-7c17-4bb6-ba9a-5a7324f30700

ViroVideo (-90 degree) - https://drive.google.com/file/d/1ZGjfZkj39zGLx_N_i6cbyEZh118kkPuT/view

My code is in the example https://github.com/viromedia/viro/issues/473

**Comment by krishanjangir** [comment]
@VikAdvani @dthian    Could you guys please have a look in the issue.  

Some downloaded videos working fine. See 
https://drive.google.com/file/d/1YgzsrUBDL18GWVyW-r2g-NrW5iu9owD2/view

But camera recored videos are not playing in right orientation.

**Comment by achuvm** [comment]
Hi @krishanjangir,

What device are you using to record these videos?

You're right in that most videos seem to work just fine, but your video is somehow presented whiled rotated 90 degrees. We've not seen this issue before and we suspect it's something to do with how that video may be encoded?

For example, this video, shot on a S8 doesn't have the issue: https://s3-us-west-2.amazonaws.com/viro/2018_11_07_11_40_35.mp4

Thanks,

**Comment by krishanjangir** [comment]
@achuvm 

No the issue is not with the video encoded.

I have created the video using camera
https://drive.google.com/open?id=170Fj_rFCnIfzdrMU0jg69ZPycuDHIfs-

and uploaded it on firebase direct (so no encoded) and played it in single ViroVideo, still there is an issue.
https://drive.google.com/open?id=1jWsI-CVZpkNTORaLeU9j6SN_Lv1n5iNO

The same is happening on iPhone also.
Please help me resolve the issue.

**Comment by krishanjangir** [comment]
@achuvm  to confirm is codec is wrong or right.

i have created a video from iPhone and uploaded it on firebase.
https://firebasestorage.googleapis.com/v0/b/odoori-de298.appspot.com/o/Videos%2FIMG_2650.MOV?alt=media&token=5390f002-30e3-45ae-96e4-d4d6baf21b79

But the video is still played -90.
https://drive.google.com/open?id=1iYTfqJ7c0HF1s_NDonAAvxLhsSZqjMnd

If i am doing rotation={[0,0,-90]} this is wrong for other videos.

Please help me resolve it asap. I have a release on this Monday.

**Comment by krishanjangir** [comment]
Hello @achuvm 

I am using device default camera to create video.  
i am using below devices
Moto 5s Plus (Android 8.1.0)
iPhone 6 (IOS 11)

As i am using device default camera so there is no encoding on my side in video's.
These videos should play in right orientation.

As i have a major release so when i can expect solution from ViroMedia for this issue.

**Comment by achuvm** [comment]
Hi @krishanjangir,

That's interesting that you see this by default on those devices. We don't see it on the iPhone 6 that we have.

This'll be fixed in our next release, however we don't have a timeline for that just yet.

Thanks,

**Comment by krishanjangir** [comment]
@achuvm 
is above issue resolved in ViroReact v2.13.0 ?

**Comment by cuongtora1996** [comment]
@krishanjangir  this issue is still appear in v2.14.0. Look like they didn't fix it.

**Comment by ManigandanRaamanathan** [comment]
@krishanjangir can provide your code for reference?
