### ISSUE TITLE
Cant run an example on Galaxy s8+

### ISSUE THREAD

**Issue by narek-t** [viromedia/viro#856]
- [ ] Review the documentation: https://docs.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/viro
  - [ ] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: Android 9
3. Version: Latest
4. Device(s): Samsung Galaxy S8+

## Description
Can't run an example with the Tesla car on my galaxy s8+. 
There is an error:
`Error: Asset not found: /Users/.../Downloads/viro-master/code-samples/js/ARCarDemo/res/tesla/object_car_2.mtl for platform: null
    at /Users/.../Downloads/viro-master/code-samples/node_modules/metro/src/Assets.js:188:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/.../Downloads/viro-master/code-samples/node_modules/metro/src/Assets.js:52:24)
    at _next (/Users/.../Downloads/viro-master/code-samples/node_modules/metro/src/Assets.js:72:9)
::1 - - [09/May/2020:20:05:26 +0000] "GET /assets/js/ARCarDemo/res/tesla/object_car_2.mtl HTTP/1.1" 404 - "-" "Dalvik/2.1.0 (Linux; U; Android 9; SM-G955F Build/PPR1.180610.011)"
`

I checked there is no such file in res folder so it seems something wrong with the demo.
Could you please help to find where is the issue from?
Thanks.

**Comment by RoyceLeonD** [comment]
@narek-t Check if your directory looks like this? https://github.com/viromedia/viro/tree/master/code-samples/js/ARCarDemo

**Comment by narek-t** [comment]
Hi @RoyceLeonD,
Appreciate for your response, I just cloned the entire directory  https://github.com/viromedia/viro
then in the folder ./code-samples ran npm install. After that edited the App.js file to have the initial scene as ArCarDemo like this:

`<ViroARSceneNavigator
          initialScene={{
            scene: arScenes['ARCarDemo'],
          }}
          apiKey={apiKey} />`

After that steps, I run an npm start, connected from my phone, and got the error message that in the first message.

The camera is working but at a random time, I'm getting the error. The error doesn't crash the app it just appears in the console.

**Comment by RoyceLeonD** [comment]
Hey, 
I haven't taken a look at the code samples in a while. Let me do the same, and I'll update you on what I find.
In the mean time could you go the the code-samples directory and run `npm list --depth=0` and post the response, it will let us know if all the packages were installed corectly.

**Comment by narek-t** [comment]
@RoyceLeonD 
Sure, here is the response 

`├── babel-jest@23.6.0
├── jest@23.6.0
├── metro-react-native-babel-preset@0.51.1
├── react@16.8.3
├── react-native@0.59.3
├── react-test-renderer@16.6.1
└── react-viro@2.16.0`

**Comment by RoyceLeonD** [comment]
@narek-t 
Alright. I think I understood the problem. For some reason you might be missing the assets. I set up a gitpod testbed for you: https://bf3b2d28-6ef5-438e-84ed-cf3deac667be.ws-us02.gitpod.io/

_Gitpod is Github's new online editor. It's super dope. I highly recommend signing up, especially if you develop on the go._

### What I did to get it working from fresh clone.
Cloned the directory. And then ran the following
`$ cd code-samples`
`$ yarn install`
`$ npm install -g ngrok`
`$ ngrok http 8081`

Updated the App.js to `<ViroARSceneNavigator initialScene={{ scene: arScenes['ARCarDemo'], }} apiKey={apiKey} />`
`$ yarn run start`

Used the viromedia testbed app and inputted the ngrok address. And it worked.

**Comment by RoyceLeonD** [comment]
> @narek-t
> Alright. I think I understood the problem. For some reason you might be missing the assets. I set up a gitpod testbed for you: https://bf3b2d28-6ef5-438e-84ed-cf3deac667be.ws-us02.gitpod.io/
> 
> _Gitpod is Github's new online editor. It's super dope. I highly recommend signing up, especially if you develop on the go._
> 
> ### Using the gitpod link.
> Everything is already set up. Just navigate to the sample-code, run ngrok. And run the files.
> `$ cd code-samples`
> `$ ngrok http 8081`
> `$ yarn run start`
> 
> ### What I did to get it working from fresh clone.
> Cloned the directory. And then ran the following
> `$ cd code-samples`
> `$ yarn install`
> `$ npm install -g ngrok`
> `$ ngrok http 8081`
> 
> Updated the App.js to `<ViroARSceneNavigator initialScene={{ scene: arScenes['ARCarDemo'], }} apiKey={apiKey} />`
> 
> Finally, just ran the files: `$ yarn run start`
> 
> Used the viromedia testbed app and inputted the ngrok address. And it worked.
> 
> Let me know if it worked.

Ignore Everything I said here. I fixed the issue. There is a bug in the code.
The gitpod workspace has a fixed version.

### Real Fix
In this file: https://github.com/viromedia/viro/blob/d3e10d1fe30e1e8862cd4ceae2002800f9bd02ed/code-samples/js/ARCarDemo/res/tesla/object_car.obj

Replace `mtllib object_car_2.mtl` => `mtllib object_car.mtl`

That fixes it.

**Comment by narek-t** [comment]
@RoyceLeonD 
Thanks, it fixes the error but I still can't see the car model in Tesla logo. I don't have a printed logo but I'm trying to scan it on my notebook screen instead, I think should work too...

**Comment by RoyceLeonD** [comment]
I don't know if every tesla logo will work. Use this: https://github.com/viromedia/viro/blob/master/code-samples/js/ARCarDemo/res/logo.png

And zoom into the tesla logo on your computer.

**Comment by Div8285** [comment]
@narek-t use the whole logo image instead of just zooming n using the tesla image. It worked for me.
@RoyceLeonD but it's not working once the phone is removed from the development server.

**Comment by RoyceLeonD** [comment]
@narek-t, Check if a printed model helps. 
@Div8285 , If the issue still persists open up a new Issue. My initial thought is: Using the Viro testbed is an unoptimal solution if you are disconnecting from metro.

Closing this issue because there have been no updates, and the bug seems to have been resolved. Thanks
