### ISSUE TITLE
ViroSceneNavigator: vrModeEnabled not switch to pre-VR (mono) mode (React Native)

### ISSUE THREAD

**Issue by minhchienwikipedia** [viromedia/viro#88]
I set vrModeEnabled={this.state.vrMode} and i use Viro360Video in VR Sence. Default vrMode = false, when i click change mode to setState vrMode = true => full VR mode (working). After i click change mod to setState vrMode = false ( back to mono mode but not woking). VR is always flicker, i don't know why. 
I doing something wrong? Or this is issue? 
Can you help me fix this!?
Thanks

**Comment by achuvm** [comment]
Hi @minhchienwikipedia,

What device are you seeing this on? A specific model would help.

It does look like we have an issue with Android devices currently, but I'm not seeing the flickering. I am seeing that the screen goes to non-VR (360) mode but renders only black.

Thanks,

Andy

**Comment by minhchienwikipedia** [comment]
I seeing this on Android S7.

**Comment by achuvm** [comment]
Hi @minhchienwikipedia,

Thanks for the update. It looks like it's a bug with our platform.

I've filed the bug and when we release a fix, we'll be sure to update this issue.

Thanks,

Andy

**Comment by minhchienwikipedia** [comment]
I just test on iOS, when i switch pre-VR (mono) mode to full VR mode but it's not working, i see VR 360 mode, but i have black screen, video not run. But if i set vrModeEnabled default = true, it's work.
 I think Viro not yet support switch mode! I hope this issue can be fix early. 
Thanks

**Comment by anhtuank7c** [comment]
I have the same problem while switching `mono` to `vr` mode.

code sample:
```
<View style={{ flex: 1 }}>
        <Text>Welcome to VR</Text>
        <ViroSceneNavigator
          apiKey="API_KEY"
          vrModeEnabled={this.state.vrModeEnabled}
          initialScene={{
            scene: () => (
              <ViroScene
                onClick={() =>
                  this.setState(prev => ({
                    vrModeEnabled: !prev.vrModeEnabled
                  }))
                }
                onRotate={(rotateState, rotationFactor, source) => {
                  console.log('onRotate', rotateState, rotationFactor, source);
                }}
              >
                <Viro360Video source={require('./360.mp4')} />
              </ViroScene>
            )
          }}
          onExitViro={this._exitViro}
        />
      </View>
```

The Navigator switched to **vr** mode, sound of video continuously run with black screen (Cannot see video content).

**Comment by anhtuank7c** [comment]
Related issue: https://github.com/viromedia/viro/issues/12#issuecomment-292441435

**Comment by dthian** [comment]
Thanks @anhtuank7c and @minhchienwikipedia, we have identified the root cause of the issue and am currently working on a fix. This thread will be updated once the fix is deployed into release.

**Comment by achuvm** [comment]
Hi all,

Thanks for reporting this issue, it has now been fixed in our React Viro v2.2.0 release:

https://docs.viromedia.com/docs/releases

Let us know if you have any other issues!

**Comment by dam00n** [comment]
Closing this issue as problem has been fixed.

**Comment by tuananhcwrs** [comment]
Hello @dam00n , @dthian 

I still get this issue with "react-viro": "2.14.0" in android app.
Do you know what causes the regression and how we can solve this?

Thanks!
